name: Compilar Proyecto con XC8

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Descargar e instalar XC8
        run: |
          pip install gdown
          gdown "https://drive.google.com/uc?id=1ug878Xi-GHbd2yhdZv0Taw3xv8tfTDqX" -O /tmp/xc8-installer.run
          chmod +x /tmp/xc8-installer.run
          sudo /tmp/xc8-installer.run --mode unattended --unattendedmodeui none --netservername localhost --LicenseType FreeMode --prefix /opt/microchip/xc8
          ls -l /opt/microchip/xc8
          
      - name: Descargar e instalar MPLAB X
        run: |
          wget -nv -O /tmp/mplabx.tar http://ww1.microchip.com/downloads/en/DeviceDoc/MPLABX-v6.00-linux-installer.tar
          tar -xf /tmp/mplabx.tar -C /tmp
          mv /tmp/MPLAB*-linux-installer.sh /tmp/mplabx_installer.sh
          chmod +x /tmp/mplabx_installer.sh
          sudo /tmp/mplabx_installer.sh --nox11 -- --unattendedmodeui none --mode unattended --ipe 0 --collectInfo 0 --installdir /opt/mplabx
          rm /tmp/mplabx_installer.sh


      - name: Generar Makefiles y compilar proyecto
        run: |
          PROJECT_DIR="firmware/ENERGY_LIGHT_V3.X"
          CONFIG="default" 
          make -C $PROJECT_DIR 
            
      - name: Generar Makefiles y compilar proyecto
        run: |
          PROJECT_DIR="firmware/ENERGY_LIGHT_V3.X"
          CONFIG="default" 
          export JAVA_TOOL_OPTIONS="-Djava.awt.headless=true"  
          /opt/mplabx/mplab_platform/bin/prjMakefilesGenerator.sh $PROJECT_DIR@$CONFIG || exit 1
          make -C $PROJECT_DIR CONF=$CONFIG build || exit 2
          
      - name: Compilar proyecto con XC8
        run: |
          /opt/microchip/xc8/bin/xc8 --chip=16F877A --opt=none firmware/ENERGY_LIGHT_V3.X/main.c

      - name: Subir artefacto compilado
        uses: actions/upload-artifact@v4
        with:
          name: firmware-hex
          path: firmware/MiProyecto.X/dist/default/production/*.hex
