name: Compilar Proyecto con XC8

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Descargar e instalar XC8
        run: |
          pip install gdown
          gdown "https://drive.google.com/uc?id=1Dx4oikTP1t-stbjv9HHKJaf_qIhtrJiL" -O /tmp/xc8-installer.run
          chmod +x /tmp/xc8-installer.run
          sudo /tmp/xc8-installer.run --mode unattended --unattendedmodeui none --netservername localhost --LicenseType FreeMode --prefix /opt/microchip/xc8
          sudo chmod -R 755 /opt/microchip/xc8
          sudo ls -l /opt/microchip/xc8

      - name: Descargar e instalar MPLAB X
        run: |
          wget -nv -O /tmp/mplabx.tar http://ww1.microchip.com/downloads/en/DeviceDoc/MPLABX-v6.00-linux-installer.tar
          tar -xf /tmp/mplabx.tar -C /tmp
          mv /tmp/MPLAB*-linux-installer.sh /tmp/mplabx_installer.sh
          chmod +x /tmp/mplabx_installer.sh
          sudo /tmp/mplabx_installer.sh --nox11 -- --unattendedmodeui none --mode unattended --ipe 0 --collectInfo 0 --installdir /opt/mplabx
          rm /tmp/mplabx_installer.sh

      - name: Verificar instalación de MPLAB X
        run: ls -l /opt/mplabx

      - name: Descargar e instalar PIC16F1xxxx DFP Pack desde Drive
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full
          sudo mkdir -p "/opt/microchip/mplabx/v6.25/packs/Microchip/PIC16F1xxxx_DFP/1.26.410"
          pip install gdown
          gdown "https://drive.google.com/uc?id=1o33lGYOxfhRTig8rJccEi6xjUGgItAUc" -O /tmp/Microchip.PIC16F1xxxx_DFP.1.26.410.atpack
          7z x /tmp/Microchip.PIC16F1xxxx_DFP.1.26.410.atpack -o"/opt/microchip/mplabx/v6.25/packs/Microchip/PIC16F1xxxx_DFP/1.26.410" -r -y
          sudo ls -l "/opt/microchip/mplabx/v6.25/packs/Microchip/PIC16F1xxxx_DFP/1.26.410/"
      
      - name: Instalar dependencias ncurses
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses6 libncursesw6

      - name: Agregar fixDeps al PATH
        run: |
          export PATH=$(find /opt/microchip -name "fixDeps" -exec dirname {} \;):$PATH
          echo "Nuevo PATH: $PATH"

      - name: Verificar fixDeps en el PATH
        run: which fixDeps || echo "fixDeps sigue sin estar en el PATH"
     

      - name: Generar Makefiles y compilar proyecto
        run: |
          export PATH=/opt/microchip/xc8/bin:/opt/mplabx/mplab_platform/bin:$PATH
          PROJECT_DIR="firmware/ENERGY_LIGHT_V3.X"
          CONFIG="default" 
          export PATH=/opt/microchip/xc8/bin:$PATH
          sudo make -C $PROJECT_DIR 

      - name: Subir artefacto compilado
        uses: actions/upload-artifact@v4
        with:
          name: firmware-hex
          path: firmware/ENERGY_LIGHT_V3.X/dist/default/production/*.hex
