name: Compilar MPLAB X con XC8

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Compilar proyecto con MPLAB X y XC8
        uses: ./
        with:
          project: firmware/ENERGY_LIGHT_V3.X  # Ajusta la ruta según tu repositorio
          configuration: default

      - name: Subir artefacto compilado
        uses: actions/upload-artifact@v4
        with:
          name: firmware-hex
          path: firmware/MiProyecto.X/dist/default/production/*.hex
