name: Compilar Proyecto con XC8

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Descargar e instalar XC8
        run: |
          pip install gdown
          gdown "https://drive.google.com/uc?id=1ug878Xi-GHbd2yhdZv0Taw3xv8tfTDqX" -O /tmp/xc8-installer.run
          chmod +x /tmp/xc8-installer.run
          sudo /tmp/xc8-installer.run --mode unattended --unattendedmodeui none --netservername localhost --LicenseType FreeMode --prefix /opt/microchip/xc8
          ls -l /opt/microchip/xc8

      - name: Verificar instalación de XC8
        run: |
          /opt/microchip/xc8/bin/xc8 --version

      - name: Compilar proyecto con XC8
        run: |
          /opt/microchip/xc8/bin/xc8 --chip=16F877A --opt=none firmware/ENERGY_LIGHT_V3.X/main.c
          # Si tienes más archivos, compílalos con su respectiva opción

      - name: Subir artefacto compilado
        uses: actions/upload-artifact@v4
        with:
          name: firmware-hex
          path: firmware/MiProyecto.X/dist/default/production/*.hex
