name: Compilar MPLAB X con XC8

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Restaurar caché de XC8
        uses: actions/cache@v3
        with:
          path: /opt/microchip/xc8
          key: xc8-v2.50

      - name: Descargar XC8 desde Google Drive usando gdown
        run: |
          pip install gdown
          gdown "https://drive.google.com/uc?id=1ug878Xi-GHbd2yhdZv0Taw3xv8tfTDqX" -O /tmp/xc8-installer.run
          ls -l /tmp # Lista los archivos descargados para verificar el nombre
          chmod +x /tmp/xc8-installer.run
          sudo /tmp/xc8-installer.run --mode unattended --unattendedmodeui none --netservername localhost --LicenseType FreeMode --prefix /opt/microchip/xc8
          ls -l /tmp/
          ls -l /opt/microchip
      - name: Verificar instalación de MPLAB X
        run: |
          ls /opt/mplabx/mplab_platform/bin/
          
      - name: Compilar proyecto con MPLAB X y XC8
        run: |
          /opt/mplabx/mplab_platform/bin/prjMakefilesGenerator.sh firmware/ENERGY_LIGHT_V3.X@default
          make -C firmware/ENERGY_LIGHT_V3.X CONF=default build
      
      - name: Subir artefacto compilado
        uses: actions/upload-artifact@v4
        with:
          name: firmware-hex
          path: firmware/MiProyecto.X/dist/default/production/*.hex
