name: Compilar Proyecto con XC8

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Descargar e instalar XC8
        run: |
          pip install gdown
          gdown "https://drive.google.com/uc?id=1Dx4oikTP1t-stbjv9HHKJaf_qIhtrJiL" -O /tmp/xc8-installer.run
          chmod +x /tmp/xc8-installer.run
          sudo /tmp/xc8-installer.run --mode unattended --unattendedmodeui none --netservername localhost --LicenseType FreeMode --prefix /opt/microchip/xc8
          sudo chmod -R 755 /opt/microchip/xc8
          sudo ls -l /opt/microchip/xc8

      - name: Descargar e instalar PIC16F1xxxx DFP Pack desde Drive
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full
          sudo mkdir -p "/opt/microchip/mplabx/v6.25/packs/Microchip/PIC16F1xxxx_DFP/1.26.410"
          pip install gdown
          gdown "https://drive.google.com/uc?id=1o33lGYOxfhRTig8rJccEi6xjUGgItAUc" -O /tmp/Microchip.PIC16F1xxxx_DFP.1.26.410.atpack
          7z x /tmp/Microchip.PIC16F1xxxx_DFP.1.26.410.atpack -o"/opt/microchip/mplabx/v6.25/packs/Microchip/PIC16F1xxxx_DFP/1.26.410" -r -y
          sudo ls -l "/opt/microchip/mplabx/v6.25/packs/Microchip/"
      

      - name: Generar Makefiles y compilar proyecto
        run: |
          PROJECT_DIR="firmware/ENERGY_LIGHT_V3.X"
          CONFIG="default" 
          export PATH=/opt/microchip/xc8/bin:$PATH
          make -C $PROJECT_DIR 

      - name: Subir artefacto compilado
        uses: actions/upload-artifact@v4
        with:
          name: firmware-hex
          path: firmware/ENERGY_LIGHT_V3.X/dist/default/production/*.hex
