name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download and install XC8 2.45
        run: |
          pip install gdown
          gdown "https://drive.google.com/uc?id=1Dx4oikTP1t-stbjv9HHKJaf_qIhtrJiL" -O /tmp/xc8-installer.run
          chmod +x /tmp/xc8-installer.run
          sudo /tmp/xc8-installer.run --mode unattended --unattendedmodeui none --netservername localhost --LicenseType FreeMode --prefix /opt/microchip/xc8
          sudo chmod -R 755 /opt/microchip/xc8
          sudo ls -l /opt/microchip/xc8

      - name: Download and install XC8 2.36
        run: |
          pip install gdown
          gdown "https://drive.google.com/uc?id=13tdi_JvjdnBvUe1n_NnJRZOpbCXHbJuk" -O /tmp/xc8-installer-236.run
          chmod +x /tmp/xc8-installer-236.run
          sudo /tmp/xc8-installer-236.run --mode unattended --unattendedmodeui none --netservername localhost --LicenseType FreeMode --prefix /opt/microchip/xc8
          sudo chmod -R 755 /opt/microchip/xc8
          sudo ls -l /opt/microchip/xc8

      - name: Download and install MPLAB X
        run: |
          wget -nv -O /tmp/mplabx.tar http://ww1.microchip.com/downloads/en/DeviceDoc/MPLABX-v6.00-linux-installer.tar
          tar -xf /tmp/mplabx.tar -C /tmp
          mv /tmp/MPLAB*-linux-installer.sh /tmp/mplabx_installer.sh
          chmod +x /tmp/mplabx_installer.sh
          sudo /tmp/mplabx_installer.sh --nox11 -- --unattendedmodeui none --mode unattended --ipe 0 --collectInfo 0 --installdir /opt/mplabx
          rm /tmp/mplabx_installer.sh

      - name: Verify de MPLAB X
        run: ls -l /opt/mplabx

      - name: Download and install PIC16F1xxxx DFP Pack
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full
          sudo mkdir -p "/opt/microchip/mplabx/v6.25/packs/Microchip/PIC16F1xxxx_DFP/1.15.191"
          pip install gdown
          gdown "https://drive.google.com/uc?id=1xC24O9ySCPmTiEa0DIF5RM0uV9FnFvoM" -O /tmp/Microchip.PIC16F1xxxx_DFP.1.15.191.atpack
          7z x /tmp/Microchip.PIC16F1xxxx_DFP.1.15.191.atpack -o"/opt/microchip/mplabx/v6.25/packs/Microchip/PIC16F1xxxx_DFP/1.15.191" -r -y
          sudo ls -l "/opt/microchip/mplabx/v6.25/packs/Microchip/PIC16F1xxxx_DFP/1.15.191/"
      
      - name: Download and install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses6 libncursesw6

      - name: Download fixDeps
        run: |
          pip install gdown
          gdown "https://drive.google.com/uc?id=1sE_fVqEaHVbSux4Ke4SEVpfgykGQ2_X_" -O /tmp/fixDeps
          chmod +x /tmp/fixDeps
          sudo mv /tmp/fixDeps /usr/local/bin/fixDeps
          sudo ls -l /usr/local/bin/fixDeps

      - name: Add fixDeps to PATH
        run: |
          export PATH=/usr/local/bin:$PATH
          echo "Nuevo PATH: $PATH"
        
      - name: Compile for WD03WS04_MB.X
        run: |
          export PATH=/opt/microchip/xc8/bin:/opt/mplabx/mplab_platform/bin:$PATH
          PROJECT_DIR="firmware/WD03WS04_MB.X"
          CONFIG="default" 
          export PATH=/opt/microchip/xc8/bin:$PATH
          sudo make -C $PROJECT_DIR 
      
      - name: Compile for HU01TE02PA07_modbus.X
        run : |
          export PATH=/opt/microchip/xc8/bin:/opt/mplabx/mplab_platform/bin:$PATH
          PROJECT_DIR="firmware/HU01TE02PA07_modbus.X"
          CONFIG="default" 
          export PATH=/opt/microchip/xc8/bin:$PATH
          sudo make -C $PROJECT_DIR
      
      - name: Compile for RD10_modbus.X
        run : |
          export PATH=/opt/microchip/xc8/bin:/opt/mplabx/mplab_platform/bin:$PATH
          PROJECT_DIR="firmware/RD10_modbus.X"
          CONFIG="default" 
          export PATH=/opt/microchip/xc8/bin:$PATH
          sudo make -C $PROJECT_DIR
      
      - name: Compile for TermistorRevH_modbus.X
        run : |
          export PATH=/opt/microchip/xc8/bin:/opt/mplabx/mplab_platform/bin:$PATH
          PROJECT_DIR="firmware/TermistorRevH_modbus.X"
          CONFIG="default"
          export PATH=/opt/microchip/xc8/bin:$PATH
          sudo make -C $PROJECT_DIR

      - name: Compile for Energy_modbus
        run : |
          export PATH=/opt/microchip/xc8/bin:/opt/mplabx/mplab_platform/bin:$PATH
          PROJECT_DIR="firmware/ENERGY_LIGHT_modbus.X"
          CONFIG="default"
          export PATH=/opt/microchip/xc8/bin:$PATH
          sudo make -C $PROJECT_DIR

      - name: Artifact WD
        uses: actions/upload-artifact@v4
        with:
          name: wd03ws04-modbus
          path: firmware/WD03WS04_MB.X/dist/default/production/WD03WS04_MB.X.production.hex
        
      - name: Artifact HuTemPres
        uses: actions/upload-artifact@v4
        with:
          name: hu01te02pa07-modbus
          path: firmware/HU01TE02PA07_modbus.X/dist/default/production/HU01TE02PA07_modbus.X.production.hex

      - name: Artifact RD
        uses: actions/upload-artifact@v4
        with:
          name: rd10-modbus
          path: firmware/RD10_modbus.X/dist/default/production/RD10_modbus.X.production.hex
      
      - name: Artifact Termistor
        uses: actions/upload-artifact@v4
        with:
          name: termistor-modbus
          path: firmware/TermistorRevH_modbus.X/dist/default/production/TermistorRevH_modbus.X.production.hex

      - name: Artifact Energy
        uses: actions/upload-artifact@v4
        with:
          name: energy-modbus
          path: firmware/ENERGY_LIGHT_modbus.X/dist/default/production/ENERGY_LIGHT_modbus.X.production.hex